# Generated by Django 4.0 on 2023-03-30 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobita', '0006_alter_comment_created_at_alter_post_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 3, 30, 16, 26, 55, 398038)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 3, 30, 16, 26, 55, 398038)),
        ),
    ]
