# Generated by Django 4.0 on 2023-05-22 20:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('kobita', '0009_delete_user_alter_comment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 5, 23, 2, 8, 16, 326900)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 5, 23, 2, 8, 16, 326900)),
        ),
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='')),
                ('address', models.TextField(max_length=1000)),
                ('bio', models.TextField(max_length=1000)),
                ('mobile', models.IntegerField()),
                ('relationship_status', models.CharField(choices=[('Married', 'Married'), ('Single', 'Single'), ('Complicated', 'Complicated'), ('Divorced', 'Divorced'), ('Separated', 'Separated'), ('Untold Story', 'Untold Story')], max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Gay', 'Gay'), ('Lesbian', 'Lesbian'), ('Trans', 'Trans'), ('Undefined', 'Undefined')], max_length=50)),
                ('extra-info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
