# Generated by Django 4.0 on 2023-05-24 06:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobita', '0010_alter_comment_created_at_alter_post_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrainfo',
            name='address',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 5, 24, 12, 8, 43, 497712)),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='gender',
            field=models.CharField(choices=[('Gay', 'Gay'), ('Lesbian', 'Lesbian'), ('Trans', 'Trans'), ('Undefined', 'Undefined'), ('Male', 'Male'), ('Female', 'Female')], max_length=50),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='picture',
            field=models.ImageField(upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='relationship_status',
            field=models.CharField(choices=[('Married', 'Married'), ('Single', 'Single'), ('Complicated', 'Complicated'), ('Divorced', 'Divorced'), ('Separated', 'Separated'), ('Untold Story', 'Untold Story'), ('Break Up', 'Break Up')], max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 5, 24, 12, 8, 43, 496715)),
        ),
    ]
