# Generated by Django 4.0 on 2023-05-27 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobita', '0011_remove_extrainfo_address_alter_comment_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extrainfo',
            old_name='extra-info',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='extrainfo',
            name='picture',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 5, 27, 16, 49, 39, 567970)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 5, 27, 16, 49, 39, 567455)),
        ),
    ]
